const ENV = process.env;

module.exports = {
  PORT: ENV.PORT || 5000,
  REDIS_URL: ENV.REDIS_URL,
  NOTIFICATIONS_API_KEY: ENV.NOTIFICATIONS_API_KEY,
  DB_URL: ENV.DB_URL_DEV || ENV.DB_URL_PROD,
  TELEGRAM_TOKEN: ENV.TELEGRAM_TOKEN_DEV || ENV.TELEGRAM_TOKEN_PROD,
};
